### ISSUE TITLE
ERROR Could not pass event PrepareAnvilEvent

### ISSUE THREAD

**Issue by Tikkle** [SquaredHelix/VanillaPlus#3] opened 2020-08-05 23:34 UTC
**Describe the bug**
ERROR Could not pass event PrepareAnvilEvent.
Still functions though.

**To Reproduce**
1. Install VanillaPlus 1.3.2 and use an Anvil

**Expected behavior**
No error print out.

**Screenshots**
[https://pastebin.com/raw/D4LxLvvn](https://pastebin.com/raw/D4LxLvvn)

**Server**
 - Java version: Java 8
 - Minecraft version: 1.16.1
 - Plugin version: 1.3.2
 - OS: Linux

**Comment by SquaredHelix** [comment] 2020-08-10 21:28
Fixed this in e840b529b11ee8d8232ad0fdbd9d4ba83b493460
The fix should be included in the next release

Thank you for your report

**Comment by Tikkle** [comment] 2020-08-11 00:41
[https://pastebin.com/raw/qTjtNcwq](https://pastebin.com/raw/qTjtNcwq)

It still occurs, however the plugin still functions as it should. I will also try updating my PaperMC.jar and update you if it occurs after the server software update.

I am using 1.3.3

EDIT: After updating to the latest Paperclip version, this error still occurs. The plugin still functions as advertised though 👍

**Comment by SquaredHelix** [comment] 2020-08-11 12:30
I could not reproduce this in my game, but I added a null check that should fix this issue. 2bed605de14948b25a5089f5740866e3cc1bd4a9
Will be included in next release 😃

**Comment by SquaredHelix** [comment] 2020-08-19 09:47
See the latest build (1.3.4), should fix this

**Closed as completed** 2020-08-20 12:00 UTC
Labels: bug
